#pragma once
enum WIDGETTYPE {EXIT, LOGOWIDGET, LOGINWIDGET, SELECTWIDGET, ITEMLISTWIDGET, GAMEWIDGET, TUTORIALWIDGET, SHOPWIDGET, STATUSWIDGET, REPLAYWIDGET};

enum TEAM {ATEAM, BTEAM};
#define ITEMTYPE_NUM 6

	enum SIGNUP {EXISTING_ID, NO_ID, NO_PWD, DIFFERENT_REPWD, SUCCESS_SIGNUP};
	enum ENTER {NOEXISTING_ID, SAME_ID, DIFFERENT_PWD, SUCCESS_ENTER};

