#pragma once
enum WIDGETTYPE {EXIT, LOGOWIDGET, LOGINWIDGET, SELECTWIDGET, GAMEWIDGET, TUTORIALWIDGET, SHOPWIDGET, STATUSWIDGET};

enum TEAM {ATEAM, BTEAM};
#define ITEMTYPE_NUM 6

	enum SIGNUP {EXISTING_ID, DIFFERENT_REPWD, SUCCESS_SIGNUP};
	enum ENTER {NOEXISTING_ID, SAME_ID, DIFFERENT_PWD, SUCCESS_ENTER};

